[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBYGEMS_VERSION = "3.3.22"  # Set the RubyGems version required by your project
  BUNDLER_VERSION = "2.3.14"    # Ensure Bundler version is compatible with your Gemfile.lock
