[build]
  command = "bundle install && bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBYGEMS_VERSION = "3.3.22"
  BUNDLER_VERSION = "2.3.14"
  RUBY_VERSION = "2.7.2"  # Specify the exact Ruby version you're using
