[build]
  command = "bundle install && npm run build"
  publish = "public"  # or the appropriate directory for your built site

[build.environment]
  RUBYGEMS_VERSION = "3.3.22"  # Specify the RubyGems version required
  BUNDLER_VERSION = "2.3.14"   # Specify Bundler version (if necessary)
